version: '3'
services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: Java-App:${BUILD_NUMBER}
    container_name: Java-App_${BUILD_NUMBER}
    ports:
      - "8081:8081"
      